[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # Allow keys that are safe to be public
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,ALLOWED_EMAIL"
  # Omit the build output directories from scanning
  SECRETS_SCAN_OMIT_PATHS = ".next,.netlify,public"
